name: 'Test'

on:
  push:
    branches:
      - main
    paths:
      - pnpm-lock.yaml
      - 'src/**'
      - .github/workflows/test.yml
      - .github/workflows/_test.yml
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - pnpm-lock.yaml
      - 'src/**'
      - .github/workflows/test.yml
      - .github/workflows/_test.yml

# See: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-test:
    # TODO: 書き換える {orgname}/{repogitory_name}/.github/workflows/_test.yml@main
    uses: style-arts-corp/obpr-sato-web/.github/workflows/_test.yml@main
    secrets: inherit
